spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _aud
            store_data_at_delete: true
            revision_field_name: revision_id
            revision_type_field_name: revision_type
