CREATE TABLE sys_revision_info (
    revision_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_timestamp BIGINT NOT NULL,
    username VARCHAR(255) NOT NULL
);

CREATE TABLE produtos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(120) NOT NULL,
    sku VARCHAR(64) NOT NULL UNIQUE,
    preco NUMERIC(19, 2) NOT NULL,
    observacao_interna VARCHAR(1000),
    criado_por VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    atualizado_por VARCHAR(255) NOT NULL,
    data_atualizacao TIMESTAMP NOT NULL
);

CREATE TABLE produtos_aud (
    id UUID NOT NULL,
    revision_id INTEGER NOT NULL,
    revision_type SMALLINT,
    nome VARCHAR(120),
    sku VARCHAR(64),
    preco NUMERIC(19, 2),
    criado_por VARCHAR(255),
    data_criacao TIMESTAMP,
    atualizado_por VARCHAR(255),
    data_atualizacao TIMESTAMP,
    CONSTRAINT pk_produtos_aud PRIMARY KEY (id, revision_id),
    CONSTRAINT fk_produtos_aud_revision FOREIGN KEY (revision_id) REFERENCES sys_revision_info (revision_id)
);

CREATE INDEX idx_produtos_sku ON produtos (sku);
CREATE INDEX idx_produtos_aud_revision_id ON produtos_aud (revision_id);
